name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Program (.exe Unpackaged)
        run: dotnet publish WallpaperScheduler.csproj -c Release -p:Platform=x64 -r win-x64 -p:SelfContained=true -p:PublishSingleFile=true -p:WindowsPackageType=None -o publish_exe

      - name: Publish Installer (.msix Packaged)
        run: dotnet publish WallpaperScheduler.csproj -c Release -p:Platform=x64 -r win-x64 -p:GenerateAppxPackageOnBuild=true -p:WindowsPackageType=MSIX -p:AppxBundle=Never -p:AppxPackageDir="${{ github.workspace }}\publish_msix"

      - name: Upload .exe Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wallpaper-scheduler-program-win-x64
          path: publish_exe/WallpaperScheduler.exe

      - name: Upload .msix Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wallpaper-scheduler-installer-win-x64
          path: publish_msix/**/*.msix